# Generated by Django 3.0.7 on 2020-06-15 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rains', '0002_auto_20200615_0217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rain',
            old_name='rain_datetime',
            new_name='date_time',
        ),
    ]
